version: '3.8'
services:
  app:
    build: .
    ports:
      - "5000:5000" # Maps your computer's port 5000 to Docker's 5000
    volumes:
      - .:/usr/src/app # "Live-sync" your code so you don't have to rebuild
    environment:
      - MONGO_URI=mongodb://db:27017/holidayDB
  db:
    image: mongo:latest
    ports:
      - "27017:27017"