services:
  app:
    build: .
    ports:
      - "5000:5000"  # Backend
      - "3000:3000"  # Frontend Default
      - "3001:3001"  # Frontend Backup (since your terminal said 3001)
    volumes:
      - .:/usr/src/app
    environment:
      - CHOKIDAR_USEPOLLING=true # This helps React "see" changes on Windows